"""FastAPI + WebSocket server for Motif."""

import asyncio
import json
import logging
import os
import shutil

from fastapi import FastAPI, File, Form, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from google.adk.runners import Runner
from google.adk.sessions import DatabaseSessionService
from google.genai import types

from backend.config import FRONTEND_URL, LOCAL_ANIMATIONS_DIR, LOCAL_CHARACTERS_DIR
from backend.agent.motif_agent import motif_agent
from backend.agent.callbacks import (
    get_state_queue,
    cleanup_session,
    record_state,
    get_unlocked_count,
    set_character_image,
    get_character_image,
    get_character_description,
    set_character_description,
    pre_generate_basic_states,
)
from backend.agent.tools import current_character_id
from backend.character.context import get_context, remove_context
from backend.animation import router as animation_router
from backend.character.creator import generate_character_images

logging.basicConfig(level=os.environ.get("LOG_LEVEL", "INFO").upper())
logger = logging.getLogger(__name__)

app = FastAPI(title="Motif")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_URL, "http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Mount local characters directory as static files
os.makedirs(LOCAL_CHARACTERS_DIR, exist_ok=True)


# --- Character creation REST endpoints ---

class GenerateCharacterRequest(BaseModel):
    character_id: str
    description: str
    user_id: str = ""


class SelectCharacterRequest(BaseModel):
    character_id: str
    image_index: int


@app.post("/api/generate-character")
async def api_generate_character(req: GenerateCharacterRequest):
    # Store description for later use in state generation
    set_character_description(req.character_id, req.description)

    # Create character directory with images/ subdirectory
    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, req.character_id)
    images_dir = os.path.join(char_dir, "images")
    os.makedirs(images_dir, exist_ok=True)

    paths = await generate_character_images(req.character_id, req.description)
    if not paths:
        return {"images": [], "error": "Generation failed"}

    # Move images to images/ subdirectory
    moved_paths = []
    for p in paths:
        # p is like "{character_id}/0.png"
        basename = os.path.basename(p)
        old_path = os.path.join(LOCAL_CHARACTERS_DIR, p)
        new_path = os.path.join(images_dir, basename)
        if os.path.isfile(old_path) and old_path != new_path:
            os.rename(old_path, new_path)
        moved_paths.append(f"/characters/{req.character_id}/images/{basename}")

    # Write meta.json
    _write_meta(req.character_id, req.user_id, req.description)

    return {"images": moved_paths}


@app.post("/api/select-character")
async def api_select_character(req: SelectCharacterRequest):
    # Build the absolute path to the selected image (now in images/ subdir)
    image_filename = f"{req.image_index}.png"
    abs_path = os.path.join(LOCAL_CHARACTERS_DIR, req.character_id, "images", image_filename)
    if not os.path.isfile(abs_path):
        # Fallback: try old location (without images/ subdir)
        abs_path_old = os.path.join(LOCAL_CHARACTERS_DIR, req.character_id, image_filename)
        if os.path.isfile(abs_path_old):
            abs_path = abs_path_old
        else:
            return {"ok": False, "error": "Image not found"}

    set_character_image(req.character_id, abs_path)

    # Update meta.json with selected image
    _update_meta_selected_image(req.character_id, image_filename)

    # Pre-generate basic state animations in background (states generated by LLM)
    asyncio.create_task(pre_generate_basic_states(req.character_id))

    # Return the URL — determine correct path
    if "images" in abs_path:
        image_url = f"/characters/{req.character_id}/images/{image_filename}"
    else:
        image_url = f"/characters/{req.character_id}/{image_filename}"

    return {"ok": True, "character_image": image_url}


@app.post("/api/upload-character")
async def api_upload_character(
    file: UploadFile = File(...),
    character_id: str = Form(...),
    description: str = Form(""),
    user_id: str = Form(""),
):
    """Accept a user-uploaded character image."""
    if file.content_type not in ("image/png", "image/jpeg", "image/webp"):
        return {"ok": False, "error": "Unsupported file type"}

    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, character_id)
    images_dir = os.path.join(char_dir, "images")
    os.makedirs(images_dir, exist_ok=True)

    dest = os.path.join(images_dir, "upload.png")

    # Read and save (convert to RGBA PNG for consistency)
    from PIL import Image
    import io

    data = await file.read()
    img = Image.open(io.BytesIO(data)).convert("RGBA")
    img.save(dest, "PNG")

    set_character_image(character_id, dest)
    if description:
        set_character_description(character_id, description)

    # Write meta.json
    _write_meta(character_id, user_id, description, selected_image="upload.png")

    asyncio.create_task(pre_generate_basic_states(character_id))
    return {"ok": True, "character_image": f"/characters/{character_id}/images/upload.png"}


# --- Character status API (replaces old session restore) ---

@app.get("/api/characters/{character_id}/status")
async def api_get_character_status(character_id: str):
    """Check if a character can be restored (files exist on disk)."""
    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, character_id)
    if not os.path.isdir(char_dir):
        return {"ok": False}

    # Check for images in images/ subdir or root
    images_dir = os.path.join(char_dir, "images")
    has_image = False
    for d in (images_dir, char_dir):
        if os.path.isdir(d):
            has_image = any(
                os.path.isfile(os.path.join(d, name))
                for name in ("upload.png", "0.png", "1.png", "2.png", "3.png")
            )
            if has_image:
                break

    if not has_image:
        return {"ok": False}

    # Check that we have state definitions and animations for this character
    ctx = get_context(character_id)
    all_states = ctx.registry.get_all()
    has_animations = any(
        ctx.library.has_animation_for_state(s) for s in all_states
    )
    if not all_states or not has_animations:
        return {"ok": False}

    return {"ok": True}


# Keep old endpoint for backward compatibility
@app.get("/api/session/{session_id}")
async def api_get_session(session_id: str):
    """Backward-compatible session restore — delegates to character status."""
    return await api_get_character_status(session_id)


# --- Characters list API ---

@app.get("/api/characters")
async def api_list_characters(user_id: str = ""):
    """List all characters for a user."""
    characters = []
    if not os.path.isdir(LOCAL_CHARACTERS_DIR):
        return {"characters": characters}

    for char_id in os.listdir(LOCAL_CHARACTERS_DIR):
        meta_path = os.path.join(LOCAL_CHARACTERS_DIR, char_id, "meta.json")
        if not os.path.isfile(meta_path):
            continue
        try:
            with open(meta_path, "r") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, IOError):
            continue

        # Filter by user_id if provided
        if user_id and meta.get("user_id") != user_id:
            continue

        # Build image URL
        image_url = _get_character_image_url(char_id, meta)

        characters.append({
            "character_id": char_id,
            "description": meta.get("description", ""),
            "image_url": image_url,
            "created_at": meta.get("created_at", ""),
        })

    # Sort by created_at descending
    characters.sort(key=lambda c: c.get("created_at", ""), reverse=True)
    return {"characters": characters}


@app.delete("/api/characters/{character_id}")
async def api_delete_character(character_id: str):
    """Delete a character and all its data."""
    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, character_id)
    if os.path.isdir(char_dir):
        shutil.rmtree(char_dir)
    remove_context(character_id)
    cleanup_session(character_id)
    return {"ok": True}


# --- States API ---

@app.get("/api/states")
async def api_get_states(character_id: str = ""):
    """Return all current state definitions for a character."""
    if character_id:
        ctx = get_context(character_id)
        return ctx.registry.get_all()
    # Fallback: return empty
    return {}


# Mount static file directories (must be AFTER route definitions)
app.mount("/characters", StaticFiles(directory=LOCAL_CHARACTERS_DIR), name="characters")

# Wire up router: invalidate embeddings when states change (for global cache)
animation_router.invalidate_cache()


@app.on_event("startup")
async def _startup_preload_model():
    """Load the semantic routing model in background — service is available immediately."""
    asyncio.create_task(animation_router.preload_model_async())

DB_PATH = os.path.join(os.path.dirname(LOCAL_CHARACTERS_DIR), "sessions.db")
session_service = DatabaseSessionService(db_url=f"sqlite+aiosqlite:///{DB_PATH}")

runner = Runner(
    agent=motif_agent,
    app_name="motif",
    session_service=session_service,
)


async def _state_msg(state: str, character_id: str) -> dict:
    """Build a state_change message, including animation_url if available.

    Uses fallback logic: if no video for this state, use rest state's video
    and trigger background generation for the missing state.
    """
    ctx = get_context(character_id)
    msg = {
        "type": "state_change",
        "state": state,
        "label": ctx.registry.get_label(state),
    }
    url, is_fallback = await ctx.library.get_animation_url_with_fallback(state)
    if url:
        msg["animation_url"] = url
    if is_fallback:
        msg["is_fallback"] = True
    # Trigger background generation if state has no own animation
    if is_fallback or (not url and ctx.registry.is_valid(state)):
        from backend.agent.callbacks import _maybe_trigger_generation
        _maybe_trigger_generation(state, character_id=character_id)
    return msg


# --- Chat history persistence ---

def _chat_history_path(character_id: str) -> str:
    return os.path.join(LOCAL_CHARACTERS_DIR, character_id, "chat_history.json")


def _load_chat_history(character_id: str) -> list[dict]:
    path = _chat_history_path(character_id)
    if not os.path.isfile(path):
        return []
    try:
        with open(path, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def _append_chat_messages(character_id: str, messages: list[dict]) -> None:
    history = _load_chat_history(character_id)
    history.extend(messages)
    path = _chat_history_path(character_id)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(history, f, ensure_ascii=False)


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.websocket("/ws/{character_id}")
async def websocket_endpoint(websocket: WebSocket, character_id: str):
    await websocket.accept()
    logger.info(f"WebSocket connected: {character_id}")

    ctx = get_context(character_id)

    # Restore character image from disk if not in memory (page refresh case)
    if not get_character_image(character_id):
        # Try reading from meta.json first
        meta = _read_meta(character_id)
        selected = meta.get("selected_image") if meta else None
        restored = False

        if selected:
            # Try images/ subdir first, then root
            for base in (
                os.path.join(LOCAL_CHARACTERS_DIR, character_id, "images"),
                os.path.join(LOCAL_CHARACTERS_DIR, character_id),
            ):
                path = os.path.join(base, selected)
                if os.path.isfile(path):
                    set_character_image(character_id, path)
                    logger.info(f"Restored character image for {character_id}: {selected}")
                    restored = True
                    break

        if not restored:
            # Fallback: scan for any image
            for search_dir in (
                os.path.join(LOCAL_CHARACTERS_DIR, character_id, "images"),
                os.path.join(LOCAL_CHARACTERS_DIR, character_id),
            ):
                if not os.path.isdir(search_dir):
                    continue
                for name in ("upload.png", "0.png", "1.png", "2.png", "3.png"):
                    path = os.path.join(search_dir, name)
                    if os.path.isfile(path):
                        set_character_image(character_id, path)
                        logger.info(f"Restored character image for {character_id}: {name}")
                        restored = True
                        break
                if restored:
                    break

    # Restore character description from meta.json
    if not get_character_description(character_id):
        meta = _read_meta(character_id)
        if meta and meta.get("description"):
            set_character_description(character_id, meta["description"])

    # Restore existing ADK session or create a new one
    session = None
    try:
        existing = await session_service.list_sessions(
            app_name="motif", user_id=character_id
        )
        if existing and existing.sessions:
            session = await session_service.get_session(
                app_name="motif",
                user_id=character_id,
                session_id=existing.sessions[-1].id,
            )
            logger.info(f"Restored ADK session for {character_id}: {session.id}")
    except Exception as e:
        logger.warning(f"Failed to restore session for {character_id}: {e}")

    if session is None:
        session = await session_service.create_session(
            app_name="motif",
            user_id=character_id,
            state={"_character_id": character_id},
        )
        logger.info(f"Created new ADK session for {character_id}: {session.id}")

    # Send initial state definitions so frontend can generate CSS
    await websocket.send_json({
        "type": "states_init",
        "states": ctx.registry.get_all(),
    })

    # Send initial state (use dynamic default instead of hardcoded "idle")
    default_state = ctx.registry.get_default_state() or "idle"
    await websocket.send_json(await _state_msg(default_state, character_id))

    # Send animation_ready for all existing animations so frontend can populate cache
    # and initialize unlock tracking for states that already have animations
    for state_name in ctx.registry.get_all():
        if ctx.library.has_animation_for_state(state_name):
            record_state(character_id, state_name, character_id=character_id)
            url = await ctx.library.get_animation_url(state_name)
            if url:
                await websocket.send_json({
                    "type": "animation_ready",
                    "state": state_name,
                    "animation_url": url,
                })

    # Send chat history
    chat_history = _load_chat_history(character_id)
    if chat_history:
        await websocket.send_json({
            "type": "chat_history",
            "messages": chat_history,
        })

    # Send initial growth count
    await websocket.send_json({
        "type": "growth",
        "total_animations": get_unlocked_count(character_id),
    })

    state_queue = get_state_queue(character_id)

    # Background task to drain state queue and push to WebSocket
    async def _drain_queue():
        try:
            while True:
                msg = await state_queue.get()
                try:
                    await websocket.send_json(msg)
                except Exception:
                    break
        except asyncio.CancelledError:
            pass

    drain_task = asyncio.create_task(_drain_queue())

    try:
        while True:
            raw = await websocket.receive_text()
            data = json.loads(raw)

            if data.get("type") != "user_message":
                continue

            user_text = data.get("text", "").strip()
            if not user_text:
                continue

            # Set contextvar for tools
            token = current_character_id.set(character_id)

            try:
                # Transition to processing state (content-driven)
                all_states = ctx.registry.get_all()
                processing_state = await animation_router.route_async(
                    user_text, all_states, fallback_role="processing",
                    embedding_cache=ctx.state_embeddings,
                )
                await websocket.send_json(await _state_msg(processing_state, character_id))
                record_state(character_id, processing_state, character_id=character_id)

                # Create content for ADK
                content = types.Content(
                    role="user", parts=[types.Part(text=user_text)]
                )

                # Run agent and stream results
                collected_text = ""

                async for event in runner.run_async(
                    user_id=character_id,
                    session_id=session.id,
                    new_message=content,
                ):
                    # Drain state queue (tool callbacks push state changes here)
                    while not state_queue.empty():
                        state_msg = await state_queue.get()
                        await websocket.send_json(state_msg)

                    # Process agent events
                    if event.content and event.content.parts:
                        for part in event.content.parts:
                            if part.text:
                                # Transition to speaking on first text (content-driven)
                                if not collected_text:
                                    speaking_state = await animation_router.route_async(
                                        part.text, all_states, fallback_role="speaking",
                                        embedding_cache=ctx.state_embeddings,
                                    )
                                    await websocket.send_json(
                                        await _state_msg(speaking_state, character_id)
                                    )
                                    record_state(character_id, speaking_state, character_id=character_id)

                                collected_text += part.text
                                await websocket.send_json(
                                    {
                                        "type": "text_chunk",
                                        "text": part.text,
                                        "done": False,
                                    }
                                )

                # Signal text completion
                if collected_text:
                    await websocket.send_json(
                        {"type": "text_chunk", "text": "", "done": True}
                    )

                # Persist chat history
                import datetime
                ts = datetime.datetime.now(datetime.timezone.utc).isoformat()
                _append_chat_messages(character_id, [
                    {"role": "user", "text": user_text, "timestamp": ts},
                    {"role": "agent", "text": collected_text, "timestamp": ts},
                ])

                # Drain any remaining state changes
                while not state_queue.empty():
                    state_msg = await state_queue.get()
                    await websocket.send_json(state_msg)

                # Send growth message with unlock count
                unlocked_count = get_unlocked_count(character_id)
                await websocket.send_json(
                    {
                        "type": "growth",
                        "total_animations": unlocked_count,
                    }
                )

                # Back to idle — route based on conversation content
                # Re-fetch states (agent may have added new ones via manage_states)
                all_states = ctx.registry.get_all()
                idle_content = user_text + " " + collected_text[:200]
                idle_state = await animation_router.route_async(
                    idle_content, all_states, fallback_role="rest",
                    embedding_cache=ctx.state_embeddings,
                )
                await websocket.send_json(await _state_msg(idle_state, character_id))
            finally:
                current_character_id.reset(token)

    except WebSocketDisconnect:
        logger.info(f"WebSocket disconnected: {character_id}")
    except Exception as e:
        logger.error(f"WebSocket error: {e}", exc_info=True)
        try:
            await websocket.send_json({"type": "error", "message": str(e)})
        except Exception:
            pass
    finally:
        drain_task.cancel()
        cleanup_session(character_id)


# --- Helper functions for meta.json ---

def _write_meta(character_id: str, user_id: str, description: str, selected_image: str = "") -> None:
    """Write meta.json for a character."""
    import datetime
    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, character_id)
    os.makedirs(char_dir, exist_ok=True)
    meta_path = os.path.join(char_dir, "meta.json")

    meta = {}
    if os.path.isfile(meta_path):
        try:
            with open(meta_path, "r") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, IOError):
            pass

    meta["user_id"] = user_id or meta.get("user_id", "")
    meta["description"] = description or meta.get("description", "")
    if selected_image:
        meta["selected_image"] = selected_image
    if "created_at" not in meta:
        meta["created_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat()

    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)


def _update_meta_selected_image(character_id: str, image_filename: str) -> None:
    """Update the selected_image field in meta.json."""
    char_dir = os.path.join(LOCAL_CHARACTERS_DIR, character_id)
    meta_path = os.path.join(char_dir, "meta.json")

    meta = {}
    if os.path.isfile(meta_path):
        try:
            with open(meta_path, "r") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, IOError):
            pass

    meta["selected_image"] = image_filename
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)


def _read_meta(character_id: str) -> dict | None:
    """Read meta.json for a character."""
    meta_path = os.path.join(LOCAL_CHARACTERS_DIR, character_id, "meta.json")
    if not os.path.isfile(meta_path):
        return None
    try:
        with open(meta_path, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return None


def _get_character_image_url(character_id: str, meta: dict) -> str:
    """Build the image URL for a character from its meta.json."""
    selected = meta.get("selected_image", "")
    if selected:
        # Check images/ subdir first
        images_path = os.path.join(LOCAL_CHARACTERS_DIR, character_id, "images", selected)
        if os.path.isfile(images_path):
            return f"/characters/{character_id}/images/{selected}"
        # Fallback to root
        root_path = os.path.join(LOCAL_CHARACTERS_DIR, character_id, selected)
        if os.path.isfile(root_path):
            return f"/characters/{character_id}/{selected}"

    # Scan for any image
    for subdir in ("images", ""):
        d = os.path.join(LOCAL_CHARACTERS_DIR, character_id, subdir) if subdir else os.path.join(LOCAL_CHARACTERS_DIR, character_id)
        if not os.path.isdir(d):
            continue
        for name in ("upload.png", "0.png", "1.png", "2.png", "3.png"):
            if os.path.isfile(os.path.join(d, name)):
                prefix = f"/characters/{character_id}/{subdir}/{name}" if subdir else f"/characters/{character_id}/{name}"
                return prefix.replace("//", "/")
    return ""


if __name__ == "__main__":
    import uvicorn
    from backend.config import HOST, PORT

    uvicorn.run(
        "backend.main:app",
        host=HOST,
        port=PORT,
    )
